name: Azure Static Web Apps CI/CD
on:
  push: { branches: [main] }
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - name: Build static site
        run: |
          npm ci
          npm run build   # builds and exports to ./out
      - name: Build & Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: out    # upload exported site
          api_location: api    # upload Functions API
