name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    timeout-minutes: 30       # gives extra headroom for large sites

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. Set up Node.js & install deps
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # 3. Build your Next.js app with proper environment
      - name: Build App
        run: npm run build
        env:
          NODE_ENV: production
          SITE_URL: https://spillmoretea.com

      # 4. Add .nojekyll file for static assets
      - name: Add .nojekyll file
        run: touch out/.nojekyll

      # 4. Deploy *only* the `out/` folder to Azure SWA
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_FOREST_0C4324B10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'                  # skip the Oryx build & only upload
          skip_app_build: true
          app_location: '/'                 # App source code path
          api_location: ''                  # API source code path - optional
          output_location: 'out'            # Built app content directory
        env:
          IS_STATIC_EXPORT: true
