name: Azure Static Web Apps CI/CD
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js site
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install API dependencies
        run: |
          if [ -f api/package.json ]; then
            npm ci --prefix api
          else
            echo "No api/package.json found; skipping API install"
          fi

      - name: Verify build artifacts
        run: |
          node -v && npm -v
          echo "Contents of repo root:" && ls -la
          echo "Contents of ./out:" && ls -la out || (echo "ERROR: ./out not found" && exit 1)
          test -f out/index.html || (echo "ERROR: out/index.html missing" && exit 1)

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: out
          api_location: api
          skip_app_build: true
          skip_api_build: true
